### ISSUE TITLE
Points position indícation inverter

### ISSUE THREAD

**Issue by pelestedt** [GMJS/gmjs_ocs#12]
There is a need to be able to define inverted logic for the indication pof a Points position. The reason is that we do not use two descrete inputs, one for left and one for right, but the analogue value on an AD input. The input voltage swings between 0 and 5VDC with 2,5V indicating not in position. It has proven difficult to change logic left and right in the hardware and hence an additional parameter is needed to change the logic for left and right positions.

**Comment by elestedt** [comment]
@pelestedt Clarifications:
  * Does this apply to both Pulse and servo motors?
  * Is it desireable to specify the analogue values used to determine position or just have a reverse flip switch?

**Comment by pelestedt** [comment]
The inverted logic for points position is needed for all types of points machines. There is no need to be able to adjust the values.
